### ISSUE TITLE
CSS changes

### ISSUE THREAD

**Issue by Tor020** [DevvitIO/DevvitIO.github.io#8]
```CSS

//Give  

a.proj-container{
 border-radius: 3rem;
}

.btn{   border-radius: 2rem;
  border: 2px white solid;
  padding: 1rem 3rem;
}

//Remove 

.proj-descr{
font-family: Libre Baskerville,serif;
```
